<?php

namespace Database\Seeders;

use App\Models\StreetType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StreetTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $data = [
        [
            "longName" => "Access",
            "shortName" => "AC",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Alley",
            "shortName" => "ALLY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Alleyway",
            "shortName" => "ALWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Amble",
            "shortName" => "AMBL",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Anchorage",
            "shortName" => "ANCG",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Approach",
            "shortName" => "APP",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Arcade",
            "shortName" => "ARC",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Artery",
            "shortName" => "ART",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Avenue",
            "shortName" => "AVE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Basin",
            "shortName" => "BASN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Beach",
            "shortName" => "BCH",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Bridge",
            "shortName" => "BDGE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Broadway",
            "shortName" => "BDWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Bende",
            "shortName" => "BEND",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Blank",
            "shortName" => "BLK",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Bowl",
            "shortName" => "BOWL",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Brae",
            "shortName" => "BRAE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Brace",
            "shortName" => "BRCE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Break",
            "shortName" => "BRK",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Brow",
            "shortName" => "BROW",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Boulevard",
            "shortName" => "BVD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Bypass",
            "shortName" => "BYPA",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Byway",
            "shortName" => "BYWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Causeway",
            "shortName" => "CAUS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Circuit",
            "shortName" => "CCT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Cul-De-Sac",
            "shortName" => "CDS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Chase",
            "shortName" => "CH",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Circle",
            "shortName" => "CIR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Close",
            "shortName" => "CL",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Colonnade",
            "shortName" => "CLDE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Circlet",
            "shortName" => "CLT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Common",
            "shortName" => "CMMN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Corner",
            "shortName" => "CNR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Centreway",
            "shortName" => "CNWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Concourse",
            "shortName" => "CON",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Cove",
            "shortName" => "COVE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Crossway",
            "shortName" => "COWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Copse",
            "shortName" => "CPS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Cicrcus",
            "shortName" => "CRCS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Crossroad",
            "shortName" => "CRD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Crescent",
            "shortName" => "CRES",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Course",
            "shortName" => "CRSE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Crossing",
            "shortName" => "CRSG",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Cross",
            "shortName" => "CRSS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Crest",
            "shortName" => "CRST",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Corso",
            "shortName" => "CSO",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Court",
            "shortName" => "CT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Centre",
            "shortName" => "CTR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Cutting",
            "shortName" => "CTTG",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Courtyard",
            "shortName" => "CTYD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Cruiseway",
            "shortName" => "CUWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Dale",
            "shortName" => "DALE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Dell",
            "shortName" => "DELL",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Deviation",
            "shortName" => "DEVN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Dip",
            "shortName" => "DIP",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Drive",
            "shortName" => "DR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Driveway",
            "shortName" => "DRWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Distributor",
            "shortName" => "DSTR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Edge",
            "shortName" => "EDGE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Elbow",
            "shortName" => "ELB",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "End",
            "shortName" => "END",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Entrance",
            "shortName" => "ENT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Esplanade",
            "shortName" => "ESP",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Estate",
            "shortName" => "EST",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Expressway",
            "shortName" => "EXP",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Extension",
            "shortName" => "EXTN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Fairway",
            "shortName" => "FAWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Firetrail",
            "shortName" => "FITR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Flat",
            "shortName" => "FLAT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Follow",
            "shortName" => "FOLW",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Formation",
            "shortName" => "FORM",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Front",
            "shortName" => "FRNT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Frontage",
            "shortName" => "FRTG",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Foreshore",
            "shortName" => "FSHR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Fire",
            "shortName" => "FTRK",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Footway",
            "shortName" => "FTWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Freeway",
            "shortName" => "FWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Gap",
            "shortName" => "GAP",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Garden",
            "shortName" => "GDN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Gardens",
            "shortName" => "GDNS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Glade",
            "shortName" => "GLD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Glen",
            "shortName" => "GLEN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Gully",
            "shortName" => "GLY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Grove",
            "shortName" => "GR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Grange",
            "shortName" => "GRA",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Green",
            "shortName" => "GRN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Ground",
            "shortName" => "GRND",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Gate",
            "shortName" => "GTE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Gates",
            "shortName" => "GTES",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Gateway",
            "shortName" => "GTWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Heath",
            "shortName" => "HETH",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Hill",
            "shortName" => "HILL",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Highroad",
            "shortName" => "HRD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Heights",
            "shortName" => "HTS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Hub",
            "shortName" => "HUB",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Highway",
            "shortName" => "HWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Interchange",
            "shortName" => "INTG",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Intersection",
            "shortName" => "INTN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Island",
            "shortName" => "ISLD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Junction",
            "shortName" => "JNC",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Key",
            "shortName" => "KEY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Lane",
            "shortName" => "LANE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Landing",
            "shortName" => "LDG",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Lees",
            "shortName" => "LEES",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Line",
            "shortName" => "LINE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Link",
            "shortName" => "LINK",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Lookout",
            "shortName" => "LKT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Laneway",
            "shortName" => "LNWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Loop",
            "shortName" => "LOOP",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Little",
            "shortName" => "LT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Lower",
            "shortName" => "LWR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Mall",
            "shortName" => "MALL",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Mew",
            "shortName" => "MEW",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Mews",
            "shortName" => "MEWS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Meander",
            "shortName" => "MNDR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Mount",
            "shortName" => "MT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Motorway",
            "shortName" => "MWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Nook",
            "shortName" => "NOOK",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Outlook",
            "shortName" => "OTLK",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Park",
            "shortName" => "PARK",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Part",
            "shortName" => "PART",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Pass",
            "shortName" => "PASS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Path",
            "shortName" => "PATH",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Parade",
            "shortName" => "PDE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Pathway",
            "shortName" => "PHWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Piazza",
            "shortName" => "PIAZ",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Parklands",
            "shortName" => "PKLD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Pocket",
            "shortName" => "PKT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Parkway",
            "shortName" => "PKWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Place",
            "shortName" => "PL",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Plateau",
            "shortName" => "PLAT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Palms",
            "shortName" => "PLM",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Plaza",
            "shortName" => "PLZA",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Point",
            "shortName" => "PNT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Port",
            "shortName" => "PORT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Promenade",
            "shortName" => "PROM",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Pursuit",
            "shortName" => "PRST",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Passage",
            "shortName" => "PSGE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Quadrangle",
            "shortName" => "QDGL",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Quadrant",
            "shortName" => "QDRT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Quad",
            "shortName" => "QUAD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Quay",
            "shortName" => "QY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Quays",
            "shortName" => "QYS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Ramp",
            "shortName" => "RAMP",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Range",
            "shortName" => "RNGE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Reach",
            "shortName" => "REACH",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Rest",
            "shortName" => "REST",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Retreat",
            "shortName" => "RTT",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Ride",
            "shortName" => "RIDE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Ridge",
            "shortName" => "RDGE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Road",
            "shortName" => "RD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Round",
            "shortName" => "RND",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Route",
            "shortName" => "RTE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Row",
            "shortName" => "ROW",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Rise",
            "shortName" => "RSE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Rotunda",
            "shortName" => "RTA",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Runway",
            "shortName" => "RUN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Service Way",
            "shortName" => "SRWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Square",
            "shortName" => "SQ",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Stairs",
            "shortName" => "STAI",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Strand",
            "shortName" => "STRD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Station",
            "shortName" => "STN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Steps",
            "shortName" => "STPS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Subway",
            "shortName" => "SBWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Superway",
            "shortName" => "SPWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Spur",
            "shortName" => "SPUR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Square",
            "shortName" => "SQR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Stroll",
            "shortName" => "STRL",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Tarn",
            "shortName" => "TARN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Terrace",
            "shortName" => "TCE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Thoroughfare",
            "shortName" => "THFR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Track",
            "shortName" => "TRCK",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Tollway",
            "shortName" => "TWY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Top",
            "shortName" => "TOP",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Tow",
            "shortName" => "TOW",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Trailer",
            "shortName" => "TRLR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Triangle",
            "shortName" => "TRI",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Trunkway",
            "shortName" => "TRKW",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Turn",
            "shortName" => "TURN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Tunnel",
            "shortName" => "TUN",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Underpass",
            "shortName" => "UPAS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Upper",
            "shortName" => "UPPR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Vale",
            "shortName" => "VALE",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Viaduct",
            "shortName" => "VIAD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "View",
            "shortName" => "VIEW",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Village",
            "shortName" => "VLLG",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Vista",
            "shortName" => "VSTA",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Villages",
            "shortName" => "VLLS",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Walk",
            "shortName" => "WALK",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Way",
            "shortName" => "WAY",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Waters",
            "shortName" => "WATR",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Wharf",
            "shortName" => "WHRF",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Wood",
            "shortName" => "WOOD",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
            "longName" => "Wynd",
            "shortName" => "WYND",
            "created_at" => now(),
            "updated_at" => now(),
        ],
        [
          "longName" => "Yard",
          "shortName" => "YARD",
          "created_at" => now(),
          "updated_at" => now(),
      ],
    ];

    StreetType::insert($data);

    }
}
