<?php
// Variables
return [
    "creatorName" => "PowerMaintenance",
    "creatorUrl" => "https://themeselection.com",
    "templateName" => "PowerMaintenance",
    "templateDescription" => "",
    "templateKeyword" => "",
    "licenseUrl" => "https://themeselection.com/license/",
    "livePreview" => "https://demos.themeselection.com/sneat-bootstrap-html-laravel-admin-template-free/demo/",
    "productPage" => "https://themeselection.com/item/sneat-bootstrap-html-laravel-admin-template/",
    "support" => "https://github.com/themeselection/sneat-html-laravel-admin-template-free/issues",
    "moreThemes" => "https://themeselection.com/",
    "documentation" => "https://themeselection.com/demo/sneat-bootstrap-html-admin-template/documentation/laravel-introduction.html",
    "repository" => "https://github.com/themeselection/sneat-html-laravel-admin-template-free",
    "facebookUrl" => "https://www.facebook.com/ThemeSelections/",
    "twitterUrl" => "https://twitter.com/Theme_Selection",
    "githubUrl" => "https://github.com/themeselection",
    "dribbbleUrl" => "https://dribbble.com/themeselection",
    "instagramUrl" => "https://www.instagram.com/themeselection/",
    "states" => ['VIC', 'SA', 'NSW', 'QLD', 'TAS', 'ACT', 'NT'],
    "card_type" => [
        'PCC',
        'HCC',
        'DVAGTPI',
        'DVAPCC',
        'QLDGSC',
        'DVA',
        'DVAGC',
    ],
];
